version: "3"
services:
  main:
    image: "project-barrybarry/firesand:latest"
    ports:
      - "127.0.0.1:55920:55820"
      - "127.0.0.1:55921:55821"
      - "127.0.0.1:55922:55822"
      - "127.0.0.1:4441:4451"
      - "127.0.0.1:4442:4452"
      - "127.0.0.1:4443:4453"
      - "127.0.0.1:4444:4454"
      - "127.0.0.1:4445:4455"
      - "127.0.0.1:16105:16106"
      - "6080:80"
    environment:
      USER: "ubuntu"
      PASSWORD: "ubuntu"
    volumes:
      - "/dev/shm:/dev/shm"
      - "${HOME}/.pki:/home/ubuntu/.pki"
      - "/home/ubuntu/.config"
      - "${HOME}/NPKI:/home/ubuntu/NPKI"
    restart: always